server:
  port: 8080

spring:
  application:
    name: cloud-consumer-order
  cloud:
    nacos:
      discovery:
        server-addr: 172.17.0.2:8848


##eureka注册
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
