server:
  port: 9527


spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    #\u7F51\u5173\u914D\u7F6E

    gateway:
      routes:
        - id: cloud-provider-payment80011
          uri: lb:\\cloud-consumer-order
          predicates:
            - Path=/order/add/**



