server:
  port: 8080


spring:
  application:
    name: cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: cloud-consumer-order80
          uri: lb://cloud-consumer-order
          predicates:
            - Path=/order/add/**,/order/query/**

        - id: websocketserver
          uri: lb://websocketserver
          predicates:
            - Path=/pos/websocket/**


